### ISSUE TITLE
A probelm about train_data

### ISSUE THREAD

**Issue by Zweo** [jeya-maria-jose/Cuff_less_BP_Prediction#2]
how to get 'cleaned_further.csv'?

**Comment by jeya-maria-jose** [comment]
I have not yet made the training data public, but it is just a smaller version of the whole data in a .csv format with ecg and ppg signals as discrete values in the columns.

**Comment by jeya-maria-jose** [comment]
@Zweo cleaned_further.csv - https://drive.google.com/file/d/19mflxMXKuGKNLUM8Uirgg1P0JeguRs7e/view
