### ISSUE TITLE
About the dataset you used

### ISSUE THREAD

**Issue by v3551G** [jeya-maria-jose/Cuff_less_BP_Prediction#5]
The data you provided contains four .mat file, with totally 12000 signals part included, I want to know the relation between the signals part and subject? for example, I dont even know how many subject contained in the dataset. 
      Can you tell me? Thank you very much.

**Comment by jeya-maria-jose** [comment]
@v3551G The total number of data points are 12000. The number of subjects are far lesser when compared to that. There were multiple data collected from the same subjects. This dataset is actually a processed version of MIMIC II from physionet. I think MIMIC II has more than 12000 data points. Please refer this paper https://ieeexplore.ieee.org/document/7168806 for the right details on number of subjects of the UCI Cuff Less BP dataset.

**Comment by v3551G** [comment]
Thanks your reply.
Based on the Fig.4(Histogram of BP) in the paper, I infer the “4254 records” described in the paper actually means 4254 samples that is finally used in experiments.
In the context of the official description of the dataset MIMIC-xxx，multiple subjects contained in the dataset, one subject contains one or more records, each record is a complete recording of BP measurements, which last for long time .
       My doubt is: I nearly can not find the relation between the preprocess details described in the paper and the  BP dataset released at UCI.
发件人: Jeya Maria Jose <notifications@github.com>
发送时间: 2020年6月30日 0:50
收件人: jeya-maria-jose/Cuff_less_BP_Prediction <Cuff_less_BP_Prediction@noreply.github.com>
抄送: V3551G <masterqkk@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [jeya-maria-jose/Cuff_less_BP_Prediction] About the dataset you used (#5)


@v3551G<https://github.com/v3551G> The total number of data points are 12000. The number of subjects are far lesser when compared to that. There were multiple data collected from the same subjects. This dataset is actually a processed version of MIMIC II from physionet. I think MIMIC II has more than 12000 data points. Please refer this paper https://ieeexplore.ieee.org/document/7168806 for the right details on number of subjects of the UCI Cuff Less BP dataset.

**Comment by jeya-maria-jose** [comment]
Yes, the paper actually means 4254 samples , not subjects. The dataset found in UCI website is already preprocessed. You can look at Kauchee et al 2015 and Kauchee et al. 2017 to know about the preprocessing steps followed to get the UCI data from Physionet MIMIC II.
